// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"ddd_demo/internal/conf"
	"ddd_demo/internal/domain/service"
	"ddd_demo/internal/infra"
	application "ddd_demo/internal/usecase/service"
)

// Injectors from wire.go:

func initApp(c *conf.Conf) (*application.UserUseCase, func(), error) {
	data, cleanup, err := infra.NewData(c)
	if err != nil {
		return nil, nil, err
	}
	userRepo := infra.NewUserRepo(data)
	userService := service.NewUserService(userRepo)
	userUseCase := application.NewUserUseCase(userService)
	return userUseCase, func() {
		cleanup()
	}, nil
}
